# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grading.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgrading.proto\"M\n\x05Grade\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0cstudent_name\x18\x02 \x01(\t\x12\x13\n\x0b\x63ourse_name\x18\x03 \x01(\t\x12\r\n\x05score\x18\x04 \x01(\x02\"\x15\n\x07GradeId\x12\n\n\x02id\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"#\n\tGradeList\x12\x16\n\x06grades\x18\x01 \x03(\x0b\x32\x06.Grade2\xb8\x01\n\x0eGradingService\x12\x1c\n\x08\x41\x64\x64Grade\x12\x06.Grade\x1a\x06.Grade\"\x00\x12\x1e\n\x08GetGrade\x12\x08.GradeId\x1a\x06.Grade\"\x00\x12!\n\x0b\x44\x65leteGrade\x12\x08.GradeId\x1a\x06.Empty\"\x00\x12$\n\x0cGetAllGrades\x12\x06.Empty\x1a\n.GradeList\"\x00\x12\x1f\n\x0bUpdateGrade\x12\x06.Grade\x1a\x06.Grade\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grading_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRADE']._serialized_start=17
  _globals['_GRADE']._serialized_end=94
  _globals['_GRADEID']._serialized_start=96
  _globals['_GRADEID']._serialized_end=117
  _globals['_EMPTY']._serialized_start=119
  _globals['_EMPTY']._serialized_end=126
  _globals['_GRADELIST']._serialized_start=128
  _globals['_GRADELIST']._serialized_end=163
  _globals['_GRADINGSERVICE']._serialized_start=166
  _globals['_GRADINGSERVICE']._serialized_end=350
# @@protoc_insertion_point(module_scope)
